language: node_js
node_js:
  - 10

cache: npm

branches:
  only:
  - main

install:
  - npm install
  - npm run build

script:
  - echo "Skipping tests"

deploy:
  provider: heroku
  api_key:
    secure: 19237f7f-8459-49c6-b670-4794986fd9da
